name: "ðŸ¤– Executar Bot (Manual)"

on:
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      # 1. Checa o cÃ³digo do repositÃ³rio
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Instala dependÃªncias
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Executa o bot
      - name: Run Betting Bot Script
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SINGLE_RUN: "true"
        run: python bot_apostas.py
